export const SET_GENRES = 'SET_GENRES'
export const SET_GENRES_SUCCESS = 'SET_GENRES_SUCCESS'
export const GENRE_ADD = 'GENRE_ADD'
export const GENRE_DELETE = 'GENRE_DELETE'

export const SET_COUNTRIES = 'SET_COUNTRIES'
export const SET_COUNTRIES_SUCCESS = 'SET_COUNTRIES_SUCCESS'
export const COUNTRY_ADD = 'COUNTRY_ADD'
export const COUNTRY_DELETE = 'COUNTRY_DELETE'

export const SET_MOVIES = 'SET_MOVIES'
export const SET_MOVIES_SUCCESS = 'SET_MOVIES_SUCCESS'
export const MOVIES_ADD = 'MOVIES_ADD'
export const MOVIES_DELETE = 'MOVIES_DELETE'